# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'secondoSlYKL.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(705, 466)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionOpen_Recent = QAction(MainWindow)
        self.actionOpen_Recent.setObjectName(u"actionOpen_Recent")
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionNo_Help_Here_Yet = QAction(MainWindow)
        self.actionNo_Help_Here_Yet.setObjectName(u"actionNo_Help_Here_Yet")
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.action_Copy = QAction(MainWindow)
        self.action_Copy.setObjectName(u"action_Copy")
        self.action_Paste = QAction(MainWindow)
        self.action_Paste.setObjectName(u"action_Paste")
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.action_Find_and_Replace = QAction(MainWindow)
        self.action_Find_and_Replace.setObjectName(u"action_Find_and_Replace")
        self.action_Add_Tasks = QAction(MainWindow)
        self.action_Add_Tasks.setObjectName(u"action_Add_Tasks")
        self.action_Duplicate_Task = QAction(MainWindow)
        self.action_Duplicate_Task.setObjectName(u"action_Duplicate_Task")
        self.action_About = QAction(MainWindow)
        self.action_About.setObjectName(u"action_About")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.calendarWidget = QCalendarWidget(self.centralwidget)
        self.calendarWidget.setObjectName(u"calendarWidget")
        self.calendarWidget.setGeometry(QRect(10, 30, 256, 190))
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(300, 40, 271, 191))
        self.TodayTab = QWidget()
        self.TodayTab.setObjectName(u"TodayTab")
        self.today_list = QListWidget(self.TodayTab)
        QListWidgetItem(self.today_list)
        self.today_list.setObjectName(u"today_list")
        self.today_list.setGeometry(QRect(10, 20, 161, 71))
        self.tabWidget.addTab(self.TodayTab, "")
        self.LastTask = QWidget()
        self.LastTask.setObjectName(u"LastTask")
        self.last_task_list = QListWidget(self.LastTask)
        self.last_task_list.setObjectName(u"last_task_list")
        self.last_task_list.setGeometry(QRect(10, 10, 151, 81))
        self.tabWidget.addTab(self.LastTask, "")
        self.RandomTask = QWidget()
        self.RandomTask.setObjectName(u"RandomTask")
        self.pushButton = QPushButton(self.RandomTask)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(20, 80, 75, 23))
        self.textBrowser = QTextBrowser(self.RandomTask)
        self.textBrowser.setObjectName(u"textBrowser")
        self.textBrowser.setGeometry(QRect(20, 20, 201, 41))
        self.tabWidget.addTab(self.RandomTask, "")
        self.radioButton = QRadioButton(self.centralwidget)
        self.radioButton.setObjectName(u"radioButton")
        self.radioButton.setGeometry(QRect(130, 310, 141, 18))
        MainWindow.setCentralWidget(self.centralwidget)
        self.tabWidget.raise_()
        self.calendarWidget.raise_()
        self.radioButton.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 705, 21))
        self.menuA_thing = QMenu(self.menubar)
        self.menuA_thing.setObjectName(u"menuA_thing")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menubar.addAction(self.menuA_thing.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuA_thing.addAction(self.actionNew)
        self.menuA_thing.addSeparator()
        self.menuA_thing.addAction(self.actionOpen)
        self.menuA_thing.addAction(self.actionOpen_Recent)
        self.menuA_thing.addSeparator()
        self.menuA_thing.addAction(self.actionSave)
        self.menuA_thing.addAction(self.actionSave_As)
        self.menuA_thing.addAction(self.actionSettings)
        self.menuA_thing.addSeparator()
        self.menuA_thing.addAction(self.actionExit)
        self.menuEdit.addAction(self.action_Copy)
        self.menuEdit.addAction(self.action_Paste)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.action_Find_and_Replace)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.action_Add_Tasks)
        self.menuEdit.addAction(self.action_Duplicate_Task)
        self.menuHelp.addAction(self.actionNo_Help_Here_Yet)
        self.menuHelp.addAction(self.action_About)
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.action_Copy)
        self.toolBar.addAction(self.action_Paste)
        self.toolBar.addAction(self.actionCut)
        self.toolBar.addAction(self.action_Add_Tasks)
        self.toolBar.addAction(self.action_Duplicate_Task)
        self.toolBar.addAction(self.action_About)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.textBrowser.clear)
        self.pushButton.clicked.connect(self.textBrowser.reload)

        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"&New...", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"&Open...", None))
        self.actionOpen_Recent.setText(QCoreApplication.translate("MainWindow", u"Open &Recent", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"&Save", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"&Exit", None))
        self.actionNo_Help_Here_Yet.setText(QCoreApplication.translate("MainWindow", u"No Help Here Yet", None))
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"Save As...", None))
        self.action_Copy.setText(QCoreApplication.translate("MainWindow", u"&Copy", None))
        self.action_Paste.setText(QCoreApplication.translate("MainWindow", u"&Paste", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
#if QT_CONFIG(shortcut)
        self.actionCut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.action_Find_and_Replace.setText(QCoreApplication.translate("MainWindow", u"&Find and Replace...", None))
        self.action_Add_Tasks.setText(QCoreApplication.translate("MainWindow", u"&Add Tasks...", None))
        self.action_Duplicate_Task.setText(QCoreApplication.translate("MainWindow", u"&Duplicate Task", None))
        self.action_About.setText(QCoreApplication.translate("MainWindow", u"&About...", None))

        __sortingEnabled = self.today_list.isSortingEnabled()
        self.today_list.setSortingEnabled(False)
        ___qlistwidgetitem = self.today_list.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("MainWindow", u"New Item", None));
        self.today_list.setSortingEnabled(__sortingEnabled)

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TodayTab), QCoreApplication.translate("MainWindow", u"Today's Task", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LastTask), QCoreApplication.translate("MainWindow", u"Last Task", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Load a thing", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.RandomTask), QCoreApplication.translate("MainWindow", u"Random Task", None))
        self.radioButton.setText(QCoreApplication.translate("MainWindow", u"RadioButton", None))
        self.menuA_thing.setTitle(QCoreApplication.translate("MainWindow", u"&File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"&Edit", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"&View", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"&Help", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

